apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  APP_ENV: "staging"
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Fase 5 K8s</title></head>
    <body>
      <h1>¡Hola Miguel! Desplegado via ConfigMap</h1>
      <p>Entorno: STAGING | Servidor Web NGINX</p>
    </body>
    </html>
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dev
type: Opaque
stringData:
  DB_PASSWORD: "SuperSecretPass2026!"
  API_KEY: "sk-proj-devops-labs-key"
