apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mi-app-gitops
  namespace: argocd
spec:
  project: default
  source:
    # Repositorio base de ejemplos de ArgoCD para la prueba inicial
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    targetRevision: HEAD
    path: guestbook
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
